server:
  port: 8081

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/gestion_hotilere
    username: username
    password: password
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:9090/realms/Gestion-Hoteliere

  mail:
    host: localhost
    port: 1025
    username: "dev"
    properties:
      mail:
        smtp:
          auth: false
          starttls:
            enable: false
          connectiontimeout: 5000
          timeout: 3000
          writetimeout: 5000

app:
  mail:
    from: "no-reply@gestionhoteliere.local"

application:
  file:
    uploads:
      photos-output-directory: ./uploads
